.Dd August 25, 2010
.Dt ANITA 1
.Os
.Sh NAME
.Nm anita
.Nd Automated NetBSD Installation and Test Application
.Sh SYNOPSIS
.Nm
.Op Fl -workdir Ar working_directory
.Op Fl -qemu-args qemu_arguments
.Ar install | boot | test | interact
.Ar URL
.Sh DESCRIPTION
.Nm
is an experimental tool for automated testing of the NetBSD
installation procedure.  Using 
.Nm , 
you can fully automate the process of downloading a NetBSD/i386
or NetBSD/amd64 distribution, installing it in a
.Ic qemu 
virtual machine, and booting the installed system.
.Pp
.Sh EXAMPLES
To install NetBSD 5.0.2/i386 from the master NetBSD FTP site, enter
.Pp
.Dl anita install http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
To boot the newly installed hard disk image and get a login prompt,
replace
.Ar install
with
.Ar interact :
.Pp
.Dl anita interact http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
When you are done interacting with the virtual machine, you can kill it by
typing control-a x.
.Pp
To run the NetBSD regression test suite on the installed system, use
.Pp
.Dl anita test http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
To install a snapshot, use something like the following (adjusting
the URL to point to a current snapshot):
.Pp
.Dl anita install http://nyftp.netbsd.org/pub/NetBSD-daily/HEAD/201001280000Z/i386/
.Pp
If you have built NetBSD locally using 
.Ic "build.sh -R" , 
you can point
.Nm
directly at the RELEASEDIR using a "file:" URL:
.Pp
.Dl anita install file:///path/to/releasedir/i386/
.Pp
or simply use an absolute pathname as shorthand for the above:
.Pp
.Dl anita install /path/to/releasedir/i386/
.Sh HOW IT WORKS
.Nm
works by "screen scraping" the sysinst output over an emulated
serial console, recognizing sysinst prompts and sending canned
responses.
.Pp
.Nm
will create a subdirectory under the current working directory
and cache the distribution sets, boot floppies, and a hard disk image
in it.  The directory name will be a unique name generated from the
URL, for example,
.Pp
.Dl work-http---ftp.netbsd.org-pub-NetBSD-NetBSD-5.0.2-i386-+a4c39
.Pp
To put the cache directory somewhere other than your current working
directory, use the
.Fl -workdir
option.
.Pp
When you rerun 
.Nm
with the same URL, files that already exist in
the cache directory will not be re-downloaded or rebuilt, so if you
run you 
.Ic "anita install"
with the same URL twice in a row, the second
run will effectively be a no-op, and if you rerun 
.Ic "anita interact" ,
the system will be booted from the existing disk image, skipping the
installation stage.  To force things to be redone, simply remove the
cache directory.  If you remove just the hard disk image file
.Pa wd0.img ,
.Ic "anita install" 
will recreate it from the cached distribution files.
.Nm
runs 
.Ic qemu
with the 
.Fl snapshot
option, so if you log in and make changes to the system, they will not
be saved to the disk image file.
.Pp
The following command line options are supported:
.Bl -tag -width indent
.It Fl -workdir Ar directory
The directory where
the cache directories are stored.  The default is ".".
.It Fl -qemu-args Ar string
Additional arguments to pass to qemu.  The arguments are given
as a single string, which may contain multiple arguments separated
by whitespace.  There is no way to pass qemu an argument containing
whitespace.
.El
.Sh BUGS
.Nm
is still a work in progress.  Currently, 
.Nm 
only knows how to install the i386 and amd64 ports, and amd64
has not been extensively tested.  It should be possible to add 
support for installing other ports - patches are welcome.  
Cross-installation setups where the machine running Anita is a
different architecture from the virtual machine being installed on
should work.
.Pp
.Nm
is likely to break whenever any significant change is made to
the sysinst user interface.
.Pp
The
.Nm
cache directories take a lot of disk space.  Figure about a
gigabyte per installed NetBSD version.
.Pp
Installing NetBSD releases older than 2.1 has not been tested.
.Pp
NetBSD releases older than 4.0 will install, but when booting
the installed image, they hang after the "root on ffs" message.
This is presumed to be a bug in 
.Ic qemu .
.Pp
NetBSD versions older than 2009-06-13 13:35:11 fail to find 
any PCI buses when run under qemu; see PRs 38729 and 42681.
.Pp
When
.Nm
is run under Linux, using a version of qemu that enables the
"kvm" kernel-mode virtualization by default, the emulated
NetBSD system hangs while probing the floppy drive.  This can be
worked around by passing Anita the command line option
.Fl -qemu-args 
.Ar -no-kvm .
.Pp
Running multithreaded programs (such as the ATF test suite) on the
emulated NetBSD system requires qemu patches that are in pkgsrc
beginning with qemu 0.12.3nb3, but are not yet in any official qemu
release.  See PR 42158 and https://bugs.launchpad.net/bugs/569760
for details.
.Pp
Installing most versions of NetBSD takes a long time with recent
versions of qemu because the bootloader countdown runs at 1/20 the
normal speed, and there is a long delay between loading the kernel and
the kernel printing its first console ouput, which can easily be
mistaken for a hang.  Please be patient. This issue is fixed in
NetBSD-current; see PR 43156 for details.
