.Dd October 24, 2010
.Dt ANITA 1
.Os
.Sh NAME
.Nm anita
.Nd Automated NetBSD Installation and Test Application
.Sh SYNOPSIS
.Nm
.Op Fl -workdir Ar working_directory
.Op Fl -qemu-args Ar qemu_arguments
.Op Fl -disk-size Ar size
.Op Fl -run Ar command
.Op Fl -sets Ar sets
.Ar install | boot | test | interact
.Ar URL
.Sh DESCRIPTION
.Nm
is an experimental tool for automated testing of the NetBSD
installation procedure.  Using 
.Nm , 
you can fully automate the process of downloading a NetBSD
distribution, installing it in a
.Ic qemu 
virtual machine, and booting the installed system.
.Pp
The NetBSD ports currently supported as targets (i.e., as the 
system to install and run under emulation) are i386, amd64, and
sparc.  The host (the system running
.Nm )
can be any NetBSD port or even another Unix-like system such 
as Linux.
.Pp
.Sh EXAMPLES
To install NetBSD 5.0.2/i386 from the master NetBSD FTP site, enter
.Pp
.Dl anita install http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
Installing NetBSD/sparc works a bit differently from i386 and amd64:
it uses an ISO image instead of a directory containing boot floppies
and sets:
.Pp
.Dl anita install http://ftp.netbsd.org/pub/NetBSD/iso/5.0.2/sparccd-5.0.2.iso
.Pp
To boot the newly installed hard disk image and get a login prompt,
replace
.Ar install
with
.Ar interact :
.Pp
.Dl anita interact http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
When you are done interacting with the virtual machine, you can kill it by
typing control-a x.
.Pp
To run the NetBSD ATF regression test suite on the installed system, use
.Pp
.Dl anita test http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
This will display the 
.Cm atf-report 
output on standard output.  Additionally, a subdirectory
.Pa atf/
is created under the cache directory, and will contain
output files from the ATF test suite: the raw
.Cm atf-run 
output in
.Pa test.tps ,
and the output from 
.Cm "atf-report -o xml"
in
.Pa test.xml .
To facilitate the further processing of the XML output into HTML,
the files
.Pa tests-results.xsl ,
.Pa tests-results.dtd ,
and 
.Pa tests-results.css
are also included.
.Pp
To install a snapshot, use something like the following (adjusting
the URL to point to a current snapshot):
.Pp
.Dl anita install http://nyftp.netbsd.org/pub/NetBSD-daily/HEAD/201001280000Z/i386/
.Dl anita install http://nyftp.netbsd.org/pub/NetBSD-daily/HEAD/201008070000Z/iso/sparccd.iso
.Pp
If you have built a NetBSD release locally using 
.Ic "build.sh -R" , 
you can point
.Nm
directly at the RELEASEDIR or ISO using a "file:" URL:
.Pp
.Dl anita install file:///path/to/releasedir/i386/
.Pp
or simply use an absolute pathname as shorthand for the above:
.Pp
.Dl anita install /path/to/releasedir/i386/
.Sh HOW IT WORKS
.Nm
works by "screen scraping" the sysinst output over an emulated
serial console, recognizing sysinst prompts and sending canned
responses.
.Pp
.Nm
will create a subdirectory under the current working directory
and cache the distribution sets, boot floppies, and a hard disk image
in it.  The directory name will be a unique name generated from the
URL, for example,
.Pp
.Dl work-http---ftp.netbsd.org-pub-NetBSD-NetBSD-5.0.2-i386-+a4c39
.Pp
To put the cache directory somewhere other than your current working
directory, use the
.Fl -workdir
option.
.Pp
When you rerun 
.Nm
with the same URL, files that already exist in
the cache directory will not be re-downloaded or rebuilt, so if you
run you 
.Ic "anita install"
with the same URL twice in a row, the second
run will effectively be a no-op, and if you rerun 
.Ic "anita interact" ,
the system will be booted from the existing disk image, skipping the
installation stage.  To force things to be redone, simply remove the
cache directory.  If you remove just the hard disk image file
.Pa wd0.img ,
.Ic "anita install" 
will recreate it from the cached distribution files.
.Pp
To ensure that the cached system state is always that of a 
freshly installed system,
.Nm
enables the 
.Ic qemu
snapshotting feature for the system disk (but not for other disks).
Therefore, if you log in and make changes to the system, they will not
be saved to the disk image file.
.Pp
.Sh OPTIONS
The following command line options are supported:
.Bl -tag -width indent
.It Fl -workdir Ar directory
The directory where
the cache directories are stored.  The default is ".".
.It Fl -qemu-args Ar string
Additional arguments to pass to qemu.  The arguments are given
as a single string, which may contain multiple arguments separated
by whitespace.  There is no way to pass qemu an argument containing
whitespace.
.It Fl -disk-size Ar size
The size of the virtual disk NetBSD gets installed on.  The default
is large enough to hold the OS installation itself, but if you need
additional space, you can specify a larger size.  The size is given in
bytes, or a suffix of k, M, G, or T can be used for kilo-, mega-,
giga-, or terabytes.
.It Fl -run Ar command
Log in to the virtual machine and execute the given shell
.Ar command
in it once it has booted.  This is only meaningful when used with the
.Ar boot
or
.Ar interact
command.  Since the command is sent to an interactive shell over the
console tty, it should be kept short and simple to avoid running into tty
limitations or quoting issues.  Also, any output from the command that
looks similar to a root shell "# " prompt is liable to be interpreted
as such.  Complex commands may be executed by preparing a disk
image containing a file system containing a shell script, and specifying
something like
.Pp
.Dl --qemu-args '-hdb disk.img' --run 'mount /dev/wd1a /mnt && /mnt/script'
.Pp
The exit status of the shell command will be returned as the exit status
of
.Nm .
.It Fl -sets Ar sets
The distribution sets to install, as a comma-separated list.
For a minimal install, use something like
.Pp
.Dl --sets kern-GENERIC,modules,base,etc
.Pp
A kernel, base, and etc must always be included.  Installing the X sets is
not supported.
.El
.Sh BUGS
.Nm
is still a work in progress.  Currently, 
.Nm 
only knows how to install the i386, amd64, and sparc ports, and
only i386 has been extensively tested.  It should be possible to add 
support for installing other ports - patches are welcome.
.Pp
.Nm
is likely to break whenever any significant change is made to
the sysinst user interface.
.Pp
The
.Nm
cache directories take a lot of disk space.  Figure about a
gigabyte per installed NetBSD version.
.Pp
Installing NetBSD releases older than 2.1 has not been tested.
.Pp
NetBSD/i386 releases older than 4.0 will install, but when booting
the installed image, they hang after the "root on ffs" message.
.Pp
NetBSD/i386 versions older than 2009-06-13 13:35:11 fail to find 
any PCI buses when run under qemu; see PRs 38729 and 42681.
.Pp
When 
.Nm
is run on a Linux host using a version of qemu that enables the
"kvm" kernel-mode virtualization by default, and is used to
boot a version of NetBSD-current newer than 2009-11-04 
14:39:17, the emulated NetBSD system hangs during boot; see
PR 44069 for details.  This issue can be worked 
around by passing Anita the command line option
.Fl -qemu-args 
.Ar -no-kvm-irqchip .
.Pp
Running multithreaded programs (such as the ATF test suite) on
an emulated i386 or amd64 system requires qemu patches that are in
pkgsrc beginning with qemu 0.12.3nb3, but are not yet in any official
qemu release.  See PR 42158 and https://bugs.launchpad.net/bugs/569760
for details.
.Pp
Installing most versions of NetBSD/i386 and NetBSD/amd64 takes a long
time with recent versions of qemu because the bootloader countdown
runs at 1/20 the normal speed, and there is a long delay between
loading the kernel and the kernel printing its first console output,
which can easily be mistaken for a hang.  Please be patient. This
issue has been worked around in NetBSD-current; see PR 43156 for
details.
