#!/usr/pkg/bin/python2.4

import sys
import re
import anita
from optparse import OptionParser

class Usage(Exception):
    def __init__(self, msg):
        self.msg = msg

def main(argv = None):
    if argv is None:
        argv = sys.argv

    parser = OptionParser(usage = "usage: %prog [options] install|boot|interact distribution")
    parser.add_option("--workdir",
		      help="store work files in DIR", metavar="DIR")
    (options, args) = parser.parse_args()

    if len(args) < 2:
	raise Usage("not enough arguments")

    distarg = args[1]
    if re.search(r'\.iso$', distarg):
	dist = anita.ISO(distarg)
    elif re.match('^[a-z0-9\.0-]+:', distarg):
	dist = anita.URL(distarg)
    else:
	raise Usage("can't figure out " + distarg)

    a = anita.Anita(dist, workdir = options.workdir)

    mode = args[0]
    if mode == 'install':
	a.install()
    elif mode == 'boot':
	a.boot()
    elif mode == 'interact':
	a.interact()
    else:
	raise Usage("unknown mode: " + mode)

if __name__ == "__main__":
    try:
        main()
    except Usage, err:
        print >>sys.stderr, err.msg
        print >>sys.stderr, "for help use --help"
        sys.exit(1)
