.Dd January 27, 2012
.Dt ANITA 1
.Os
.Sh NAME
.Nm anita
.Nd Automated NetBSD Installation and Test Application
.Sh SYNOPSIS
.Nm
.Op Fl -workdir Ar work_directory
.Op Fl -vmm-args Ar vmm_arguments
.Op Fl -disk-size Ar size
.Op Fl -run Ar command
.Op Fl -sets Ar sets
.Op Fl -test-timeout Ar timeout
.Op Fl -persist
.Ar mode
.Ar URL
.Sh DESCRIPTION
.Nm
is an experimental tool for automated testing of the NetBSD
installation procedure.  Using 
.Nm , 
you can fully automate the process of downloading a NetBSD
distribution, installing it in a
.Ic qemu 
virtual machine, and booting the installed system.
.Pp
The NetBSD ports currently supported as targets (i.e., as the 
system to install and run under emulation) are i386, amd64, and
sparc.  The host (the system running
.Nm )
can be any NetBSD port or even a different Unix-like system such 
as Linux, FreeBSD, or Mac OS X.
.Pp
.Sh EXAMPLES
To install NetBSD 5.0.2/i386 from the master NetBSD FTP site, enter
.Pp
.Dl anita install http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
Installing NetBSD/sparc works a bit differently from i386 and amd64:
it uses an ISO image instead of a directory containing boot floppies
and sets:
.Pp
.Dl anita install http://ftp.netbsd.org/pub/NetBSD/iso/5.0.2/sparccd-5.0.2.iso
.Pp
To boot the newly installed hard disk image and get a login prompt,
replace
.Ar install
with
.Ar interact :
.Pp
.Dl anita interact http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
When you are done interacting with the virtual machine, you can kill it by
typing control-a x.
.Pp
To run the ATF regression test suite on the installed system, use
.Pp
.Dl anita test http://ftp.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/
.Pp
.Pp
To install a snapshot, use something like the following (adjusting
the URL to point to a current snapshot):
.Pp
.Dl anita install http://nyftp.netbsd.org/pub/NetBSD-daily/HEAD/201001280000Z/i386/
.Dl anita install http://nyftp.netbsd.org/pub/NetBSD-daily/HEAD/201008070000Z/iso/sparccd.iso
.Pp
If you have built a NetBSD release locally using 
.Ic "build.sh -R" , 
you can point
.Nm
directly at the RELEASEDIR or ISO using a "file:" URL:
.Pp
.Dl anita install file:///path/to/releasedir/i386/
.Pp
or simply use an absolute pathname as shorthand for the above:
.Pp
.Dl anita install /path/to/releasedir/i386/
.Sh HOW IT WORKS
.Nm
works by "screen scraping" the sysinst output over an emulated
serial console, recognizing sysinst prompts and sending canned
responses.
.Pp
.Nm
will create a work directory and cache the distribution sets, boot 
floppies, and a hard disk image in it.  By default, the work directory
is a subdirectory of the current working directory, with a unique
name automatically generated from the distribution URL, for example,
.Pp
.Dl work-http---ftp.netbsd.org-pub-NetBSD-NetBSD-5.0.2-i386-+a4c39
.Pp
You can also specify the name of the work directory explicitly using
the 
.Fl -workdir
option.
.Pp
When you rerun 
.Nm
with the same URL, files that already exist in
the work directory will not be re-downloaded or rebuilt, so if you
run you 
.Ic "anita install"
with the same URL twice in a row, the second
run will effectively be a no-op, and if you rerun 
.Ic "anita interact" ,
the system will be booted from the existing disk image, skipping the
installation stage.  To force things to be redone, simply remove the
work directory.  If you remove just the hard disk image file
.Pa wd0.img ,
.Ic "anita install" 
will recreate it from the cached distribution files.
.Pp
To ensure that the cached system state is always that of a 
freshly installed system,
.Nm
enables the 
.Ic qemu
snapshotting feature for the system disk by default (but not for other disks).
Therefore, if you log in and make changes to the system, they will not
be saved to the disk image file.  To override this behavior, specify the
.Ar -persist
option.
.Pp
.Sh MODES
The operation performed by 
.Nm 
is determined by the 
.Ar mode
argument, which takes the following values:
.Bl -tag -width indent
.It Ar install
Install NetBSD if not already installed.
.It Ar boot
Install NetBSD if not already installed, then boot the 
installed system.
.It Ar interact
Install NetBSD if not already installed, then boot it and connect
the serial console to the terminal for interactive use.  The 
.Cm qemu
escape character control-a is in effect; for example, you can use
control-a x to exit, control-a c to enter the
.Cm qemu
monitor, or control-a b to send a break (useful for entering DDB).
.It Ar test
Install NetBSD if not already installed, then boot it and 
run the ATF test suite.  The 
.Cm atf-report 
output will be displayed on standard output.  Additionally, a
subdirectory
.Pa atf/
is created under the work directory, and will contain
output files from the ATF test suite: the raw
.Cm atf-run 
output in
.Pa test.tps ,
and the output from 
.Cm "atf-report -o xml"
in
.Pa test.xml .
To facilitate the further processing of the XML output into HTML,
the files
.Pa tests-results.xsl ,
.Pa tests-results.dtd ,
and 
.Pa tests-results.css
are also included.
.It Ar print-workdir
Print the pathname of the work directory on standard output.
This is intended for use by scripts that need to access files
in the work directory, particularly when the
.Fl -workdir
option is not used but the name of the directory is automatically
generated.
.El
.Sh OPTIONS
The following command line options are supported:
.Bl -tag -width indent
.It Fl -workdir Ar directory
The work directory.  The default is an automatically generated
name under ".".
.It Fl -vmm-args Ar string
Additional arguments to pass to the virtual machine monitor (currently
qemu, but others may be supported in the future).  The arguments are given
as a single string, which may contain multiple arguments separated
by whitespace.  There is no way to pass an argument containing
whitespace.  This option was previously called
.Fl -qemu-args ;
the old name is still accepted for backwards compatibility.
.It Fl -disk-size Ar size
The size of the virtual disk NetBSD gets installed on.  The default
is large enough to hold the OS installation itself when also using
default values for the 
.Fl -sets
and 
.Fl -memory-size
options, but if you need
additional space, you can specify a larger size.  The size is given in
bytes, or a suffix of k, M, G, or T can be used for kilo-, mega-,
giga-, or terabytes.
.It Fl -memory-size Ar size
The size of the virtual RAM.  The size is given in
bytes, or a suffix of k, M, or G can be used as with 
the 
.Fl -disk-size
option.  The default is 32M.  Note that since sysinst sizes the
swap partition based on the amount of RAM, if you run
.Cm anita install
with a large
.Fl -memory-size ,
you may also have to increase
.Fl -disk-size .
.It Fl -run Ar command
Log in to the virtual machine and execute the given shell
.Ar command
in it once it has booted.  This is only meaningful when used with the
.Ar boot
or
.Ar interact
command.  Since the command is sent to an interactive shell over the
console tty, it should be kept short and simple to avoid running into tty
limitations or quoting issues.  Also, any output from the command that
looks similar to a root shell "# " prompt is liable to be interpreted
as such.  Complex commands may be executed by preparing a disk
image containing a file system containing a shell script, and specifying
something like
.Pp
.Dl --vmm-args '-hdb disk.img' --run 'mount /dev/wd1a /mnt && /mnt/script'
.Pp
The exit status of the shell command will be returned as the exit status
of
.Nm .
.It Fl -sets Ar sets
The distribution sets to install, as a comma-separated list.
For a minimal install, use something like
.Pp
.Dl --sets kern-GENERIC,modules,base,etc
.Pp
A kernel, base, and etc must always be included.  Installing the X11 sets
is not supported.
.It Fl -test-timeout Ar timeout
Set a timeout for the tests run in the
.Cm test
mode, in seconds.  The default is 7200 seconds (two hours).
.It Fl -persist
Store any changes to the contents of the system disk persistently,
such that they may affect future
.Nm
runs, instead of the default behavior where only the 
.Ar install
mode can modify the disk contents and all other modes work with
an ephemeral snapshot copy of the freshly installed system.
.El
.Sh BUGS
.Nm
is still a work in progress.  Currently,
.Nm 
only knows how to install the i386, amd64, and sparc ports, and only
i386 and amd64 have been extensively tested.  It should be possible to
add support for installing other ports - patches are welcome.
.Pp
.Nm
is likely to break whenever any significant change is made to
the sysinst user interface.
.Pp
The
.Nm
work directories take a lot of disk space.  Figure about a
gigabyte per installed NetBSD version.
.Pp
Installing NetBSD releases older than 2.1 has not been tested.
.Pp
NetBSD/i386 releases older than 4.0 will install, but when booting
the installed image, they hang after the "root on ffs" message.
.Pp
NetBSD/i386 versions older than 2009-06-13 13:35:11 fail to find 
any PCI buses when run under qemu; see PRs 38729 and 42681.
.Pp
When 
.Nm
is run on a Linux host using a version of qemu that enables the
"kvm" kernel-mode virtualization by default, and is used to
boot a version of NetBSD-current newer than 2009-11-04 
14:39:17, the emulated NetBSD system hangs during boot; see
PR 44069 for details.  This issue can be worked 
around by passing Anita the command line option
.Fl -vmm-args 
.Ar -no-kvm
to disable kvm.  The alternative 
.Fl -vmm-args 
.Ar -no-kvm-irqchip
performs better but doesn't quite work: the system installs and
boots, but the ATF tests occasionally fail to complete; see PR 44176.
.Pp
Running multithreaded programs (such as the ATF test suite) on
an emulated i386 or amd64 system requires qemu patches that are in
pkgsrc beginning with qemu 0.12.3nb3. They were finally integrated 
into qemu on 2011-12-11, but are not yet in any official qemu 
release at the time of this writing.  See PR 42158 and 
https://bugs.launchpad.net/bugs/569760 for details.
.Pp
When attempting to install NetBSD-current in qemu 1.0, it panics
during the install kernel boot due to a regression in qemu's
emulation of the PCI configuration registers.  The work-around 
is to use qemu 0.xx.  See PR 45671 and 
https://bugs.launchpad.net/qemu/+bug/897771 for details.
.Pp
Installing most versions of NetBSD/i386 and NetBSD/amd64 takes a long
time with recent versions of qemu because the bootloader countdown
runs at 1/20 the normal speed, and there is a long delay between
loading the kernel and the kernel printing its first console output,
which can easily be mistaken for a hang.  Please be patient. This
issue has been worked around in NetBSD-current; see PR 43156 for
details.
