#!/bin/sh

exec >testsuite.log 2>&1

python=python2.6	# on guesthouse or guru

set -x -e

#./anita install /usr/build/20080708-1545/release/iso/i386cd.iso

runtest() {
    mode=$1
    shift
    workdir=`$python ./anita print-workdir "$@"`
    rm -f $workdir/wd0.img
    $python ./anita $mode "$@"
}

runtest install http://ftp.netbsd.org/pub/NetBSD/NetBSD-archive/NetBSD-2.1/i386/

runtest install http://ftp.netbsd.org/pub/NetBSD/NetBSD-archive/NetBSD-3.0.1/i386/

runtest boot http://ftp.fi.netbsd.org/pub/NetBSD/NetBSD-4.0/i386/

runtest boot http://ftp.fi.netbsd.org/pub/NetBSD/NetBSD-5.0.2/i386/

# Anita 1.2 compatibility.
$python <<END
import anita
ver = anita.Release("5.0.2")
ver.install()
END

$python ./anita --sets=kern-GENERIC,base,etc,games --run "/usr/games/factor 1234567" boot http://ftp.netbsd.org/pub/NetBSD/iso/5.0.2/sparccd-5.0.2.iso | tee stdout
grep "127 9721" stdout
rm -f stdout

url=http://ftp.fi.netbsd.org/pub/NetBSD/NetBSD-5.1/i386/
workdir=`$python ./anita print-workdir $url`
rm -f $workdir/wd0.img
$python ./anita --sets=kern-GENERIC,etc,base,tests,games,misc test $url | tee stdout || true
grep 'passed test cases' stdout
rm -f stdout

echo "pass"
